---
title: "Analyse d’un jeu de données"
author: "Guillaume LA & Samy OULMANE"
date: "2018/2019"
output:
  html_notebook: default
  html_document:
    toc: true
    toc_float:
      collapsed: false
subtitle: "Projet du 2e semestre - DFGSM3 - UE11 parcours d'informatique biomédicale"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libs
library(readr)
library(tidyverse)
library(DT)
library(desctable)
library(cowplot)
library(corrplot)
library(RColorBrewer)
```

***

## Analyse descriptive

### Analyse du fichier de diagnostics

```{r diag_nettoyage, message=FALSE}

# Importation des données
wdbc <- read_csv("data/wdbc.data", col_names = FALSE)

# Nom des colonnes
colnames(wdbc)<- c("id",
                   "diagnosis",
                   "radius_mean",
                   "texture_mean",
                   "perimeter_mean",
                   "area_mean",
                   "smoothness_mean",
                   "compactness_mean",
                   "concavity_mean",
                   "concave_points_mean",
                   "symmetry_mean", 
                   "fractal_dimension_mean",
                   "radius_se",
                   "texture_se",
                   "perimeter_se",
                   "area_se",
                   "smoothness_se",
                   "compactness_se",
                   "concavity_se",
                   "concave_points_se",
                   "symmetry_se", 
                   "fractal_dimension_se",
                   "radius_worst",
                   "texture_worst",
                   "perimeter_worst",
                   "area_worst",
                   "smoothness_worst",
                   "compactness_worst",
                   "concavity_worst",
                   "concave_points_worst",
                   "symmetry_worst", 
                   "fractal_dimension_worst")

features <- c("radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean", "compactness_mean", "concavity_mean", "concave_points_mean", "symmetry_mean", "fractal_dimension_mean", "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst", "compactness_worst", "concavity_worst", "concave_points_worst", "symmetry_worst", "fractal_dimension_worst")

wdbc$diagnosis <- factor(wdbc$diagnosis)

```


```{r diag_desc}
# Description
desctable(wdbc) %>% datatable
```


```{r diag_graphs, fig.width=10, fig.align='center'}
# Graphiques
draw_g <- function(value = "radius_mean") {
  ggplot(data = wdbc) +
    aes_string(x = value, fill = "diagnosis") +
    geom_density(adjust = 1) +
    theme_minimal() +
    theme(legend.position = 'none')
}
lapply(features, draw_g) -> a
plot_grid(plotlist = a)


wdbc_mean <- wdbc[,3:12]
wdbc_worst <- wdbc[,23:32]
M <-cor(wdbc_mean)
W <- cor(wdbc_worst)
corrplot(M, type="upper", method="number", order="hclust",
         col=brewer.pal(n=8, name="RdYlBu"), diag=FALSE)

```

