---
title: "Analyse d’un jeu de données"
author: "Guillaume LA & Samy OULMANE"
date: "2018/2019"
output:
  html_document:
    df_print: kable
    toc: true
    number_sections: true
    toc_float:
      collapsed: false
subtitle: "Projet du 2e semestre - DFGSM3 - UE11 parcours d'informatique biomédicale"
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", fig.width = 10)

# Libs
library(plyr)
library(readr)
library(tidyverse)
library(DT)
library(desctable)
library(cowplot)
library(corrplot)
library(RColorBrewer)
library(NbClust)
library(factoextra)
library(dendextend)

# Importation des données ####
wdbc <- read_csv("../data/wdbc.data", col_names = FALSE)

# Nom des colonnes
colnames <- c("radius", "texture", "perimeter", "area", "smoothness", "compactness", "concavity",  "concave_points", "symmetry",  "fractal_dimension")
variables <- gsub("_", " ", colnames) %>% str_to_title
colnames_mean <- paste0(colnames, "_mean")
colnames_se <- paste0(colnames, "_se")
colnames_worst <- paste0(colnames, "_worst")
colnames(wdbc) <- c("id", "diagnosis", colnames_mean, colnames_se, colnames_worst)

## Diagnosis en numérique (B=1, M=2)
wdbc2 <- wdbc
wdbc2$diagnosis <- revalue(wdbc$diagnosis, c("B"="1", "M"="2")) %>% as.numeric

## Données sans id ni diagnosis
wdbc_blind <- wdbc[c(-1, -2)]
## Application de scale
wdbc_scaled <- wdbc_blind %>% apply(2, FUN=scale) %>% as.data.frame

var_pert <- c("concave_points_worst", "perimeter_worst", "concave_points_mean", "perimeter_mean", "concavity_mean", "concavity_worst", "compactness_mean", "compactness_worst", "perimeter_se" )

wdbc_scaled2 <- wdbc_scaled %>% select(var_pert)

km_perf <- function (model) {
  attach(model)
  df <- data.frame(paste0("Cluster 1 : ", round(withinss[1], 2), "<br>Cluster 2 : ", round(withinss[2], 2)), round(totss, 2), round(tot.withinss, 2), round(betweenss, 2))
  return(knitr::kable(df,col.names = c("Somme intra-cluster", "Somme totale", "Somme totale intra-cluster", "Somme inter-cluster"), align = "l"))
  detach(model)
}
```

***

# Clustering

## Clustering hiérarchique

Les résultats d'un clestering hiérarchiques sont visualisables avec un **dendrogramme**.

```{r eval=F}
# Construction du modèle
model_hc <- dist(wdbc_scaled) %>% hclust(method = "ward.D") %>% as.dendrogram()
# On coupe le denrogramme de sorte à n'avoir que deux clusters
model_hc_cluster <- model_hc %>% cutree(2)
# VIsualisation
fviz_dend(model_hc, 2)
# Taille des clusters
questionr::freq(model_hc_cluster, valid = F)
```


